#!/bin/sh

modprobe dwc2
modprobe configfs
modprobe libcomposite
mount -t configfs none /sys/kernel/config

G=/sys/kernel/config/usb_gadget/g1

mkdir -p $G
echo 0x1d6b > $G/idVendor    # Linux Foundation
echo 0x0104 > $G/idProduct   # Multifunction Composite Gadget

mkdir -p $G/strings/0x409
echo "1234567890" > $G/strings/0x409/serialnumber
echo "MilkV" > $G/strings/0x409/manufacturer
echo "Duo USB Network" > $G/strings/0x409/product

mkdir -p $G/configs/c.1/strings/0x409
echo "ECM network" > $G/configs/c.1/strings/0x409/configuration

# Create ECM interface
mkdir -p $G/functions/ecm.usb0
echo "02:12:34:56:78:9a" > $G/functions/ecm.usb0/host_addr
echo "02:aa:bb:cc:dd:ee" > $G/functions/ecm.usb0/dev_addr

# Link function to configuration
ln -s $G/functions/ecm.usb0 $G/configs/c.1/

# Enable gadget
UDC=$(ls /sys/class/udc | head -n 1)
echo $UDC > $G/UDC

# Assign IP
ifconfig usb0 10.42.0.1 up
# ip a add 10.42.0.1/24 dev usb0
# ip link set usb0 mtu 512
# ip link set usb0 up 

